import {env} from 'cloudflare:workers';
import {NextRequest,NextResponse} from 'next/server';
import {getRawDb} from '@/db';
import {createSearchContext,executeSearchItem} from '@/lib/search-service';
import {digest,INSERT_SNAPSHOT,snapshotValues} from '@/lib/query-journal';
import {snapshotChanges} from '@/lib/cognitive';
import type {SearchItem,SearchSnapshot} from '@/lib/validated-search';
export const dynamic='force-dynamic';
export async function POST(request:NextRequest,context:{params:Promise<{id:string}>}){const owner=request.headers.get('oai-authenticated-user-id');if(!owner)return NextResponse.json({error:'Acesso autenticado necessário.'},{status:401});try{const {id}=await context.params,db=getRawDb(),row=await db.prepare('SELECT snapshot FROM query_history WHERE id=? AND owner_id=?').bind(id,owner).first<{snapshot:string}>();if(!row)return NextResponse.json({error:'Consulta não encontrada.'},{status:404});const before=JSON.parse(row.snapshot) as SearchSnapshot,item:SearchItem=before.request?{...before.request,key:'0'}:{key:'0',prefix:before.prefix,part:before.part,kind:before.query===`${before.prefix} → ${before.part}`?'part':'query',query:before.query},ctx=await createSearchContext(owner,before.sourceMode,env.ASSETS!,db),after=await executeSearchItem(item,ctx,{runId:crypto.randomUUID(),sourceMode:before.sourceMode,recentDays:before.recentDays}),hash=await digest(JSON.stringify({item,days:before.recentDays,sourceMode:before.sourceMode})),changes=snapshotChanges(before,after);await db.batch([db.prepare(INSERT_SNAPSHOT).bind(...snapshotValues(owner,hash,after)),db.prepare('INSERT INTO audit_events(id,owner_id,subject_id,kind,actor,created_at,payload) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),owner,id,'comparison',owner,after.queriedAt,JSON.stringify({newQueryId:after.id,changes}))]);return NextResponse.json({before,after,changes,saved:true},{headers:{'Cache-Control':'no-store'}})}catch{return NextResponse.json({error:'Não foi possível comparar agora. A consulta original permanece preservada.'},{status:503})}}
