import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {analyzeStock,parseBatch,sheetRecords,resolvePart} from '../lib/validated-search.ts';
import {saveSnapshots,digest} from '../lib/query-journal.ts';
import {parseImportCsv,validateImportRow} from '../lib/import-pipeline.ts';
const catalog=JSON.parse(fs.readFileSync(new URL('../public/data/catalog.json',import.meta.url),'utf8'));
const vehicle=JSON.parse(fs.readFileSync(new URL('../public/data/154.json',import.meta.url),'utf8'));
const parent=catalog.standardizedParts.find(p=>p.name==='Bico Injetor');
const row=(extra={})=>({id:'EXT-10',source:'EXTRATO GERAL',sourceFile:'EXTRATO GERAL.xlsx',sourceLine:10,document:'7001',prefix:'55154',part:'BICO INJETOR '+parent.codes[0],code:parent.codes[0],family:'Motor',date:'2026-09-01',time:null,km:82450,quantity:1,responsible:'80051',workOrder:'349357',movement:'issue',explicitIssue:true,note:null,...extra});
const item={key:'0',prefix:'55154',part:'Bico Injetor'};
const options={knownVehicle:true,now:new Date('2026-09-28T12:00:00Z'),recentDays:180,sourceMode:'sheets',sourceVersion:'v1',runId:'TEST-RUN-00000001'};
const analyze=(records,overrides={})=>analyzeStock(item,records,catalog,{...options,...overrides});
test('último registro sem comprovação não substitui a última saída validada',()=>{const r=analyze([row(),row({id:'EXT-11',sourceLine:11,date:'2026-09-20',document:null,explicitIssue:false})]);assert.equal(r.latest.document,'7001');assert.equal(r.latest.date,'2026-09-01');assert.equal(r.status,'validated');assert.equal(r.excludedCount,1);assert.equal(r.observed.date,'2026-09-20');});
test('origem, NUMREG, quantidade e data são requisitos independentes',()=>{for(const missing of [{document:null},{sourceFile:''},{sourceLine:null},{quantity:null},{quantity:0},{explicitIssue:false},{date:'2026-02-30'},{date:'2026-10-01'},{note:'RESERVADO, não retirado'}]){const r=analyze([row(missing)]);assert.equal(r.validated,false,JSON.stringify(missing));assert.equal(r.latest,null)}});
test('devolução ou estorno associado exclui a saída e preserva a evidência',()=>{for(const movement of ['return','reversal']){const r=analyze([row(),row({id:'NEG',sourceLine:11,date:'2026-09-02',quantity:-1,movement,explicitIssue:false})]);assert.equal(r.validated,false);assert.equal(r.status,'unconfirmed');assert.equal(r.evidence.length,2)}});
test('movimento de outra OS/documento não cancela uma saída',()=>{const r=analyze([row(),row({id:'NEG',date:'2026-09-02',document:'8001',workOrder:'8002',quantity:-1,movement:'return',explicitIssue:false})]);assert.equal(r.validated,true)});
test('empate sem horário e empate de horário permanecem inconclusivos',()=>{for(const time of [null,'09:30']){const r=analyze([row({time}),row({id:'EXT-12',sourceLine:12,document:'7002',time})]);assert.equal(r.status,'inconclusive');assert.equal(r.validated,false);assert.equal(r.latest,null)}});
test('horários explícitos ordenam saídas no mesmo dia',()=>{const r=analyze([row({time:'08:30'}),row({id:'EXT-12',sourceLine:12,document:'7002',time:'14:32'})]);assert.equal(r.latest.document,'7002');assert.equal(r.latest.time,'14:32')});
test('KM ausente não é preenchido e antiguidade é configurável',()=>{const r=analyze([row({km:null,responsible:null})]);assert.equal(r.status,'incomplete');assert.equal(r.latest.km,null);assert.equal(r.validated,true);const old=analyze([row({date:'2025-01-01'})]);assert.equal(old.status,'old');assert.equal(old.isOld,true);assert.equal(analyze([row({date:'2025-01-01'})],{recentDays:730}).status,'validated')});
test('diferencia ausência, movimentos e veículo desconhecido',()=>{assert.equal(analyze([]).status,'not_found');assert.equal(analyze([row({movement:'return',quantity:-1,explicitIssue:false})]).status,'movement_only');assert.equal(analyze([],{knownVehicle:false}).status,'vehicle_unknown');assert.equal(analyze([row({prefix:'55155'})]).status,'not_found')});
test('seleção material + código resolve exatamente o código escolhido',()=>{const m=catalog.materials.find(m=>m.code&&m.canonical);assert.deepEqual([...resolvePart(`${m.canonical} ${m.code}`,catalog).codes],[m.code]);assert.equal(resolvePart('turbina',catalog).name,'Bi turbo/Turbina')});
test('lote de 20 veículos e 5 peças produz 100 combinações independentes',()=>{const text=Array.from({length:20},(_,i)=>`${i+1} → Bico Injetor, Biturbo, Kit de Embreagem, Óleo Motor, Filtro de Ar`).join('\n');const p=parseBatch(text);assert.equal(p.errors.length,0);assert.equal(p.items.length,100);assert.equal(new Set(p.items.map(i=>i.key)).size,100);assert.equal(new Set(p.items.map(i=>i.prefix)).size,20)});
test('lote reúne repetidos, rejeita fora da frota e não trunca lotes grandes',()=>{const p=parseBatch('1 → Bico Injetor\n55001 → Bico Injetor\n800 → Biturbo\n559 → Óleo Motor');assert.equal(p.items.length,2);assert.equal(p.duplicates,1);assert.equal(p.errors.length,1);const large=parseBatch(Array.from({length:501},(_,i)=>`1 → Peça ${i}`).join('\n'));assert.equal(large.items.length,501);assert.ok(large.errors.length)});
test('CSV exige natureza explícita para saída; conserva linha e horário',()=>{const raw=parseImportCsv('Identificador;Prefixo;Peça;Data;Origem;Quantidade;Natureza;Hora\nMOV-1;154;Bico Injetor;01/09/2026;EXTRATO;1;Saída;08:32\nMOV-2;154;Bico Injetor;01/09/2026;EXTRATO;1;;');const a=validateImportRow(raw[0]);assert.equal(a.candidate.movementEvidence,'explicit');assert.equal(a.candidate.time,'08:32');assert.equal(a.candidate.sourceLine,2);const b=validateImportRow(raw[1]);assert.equal(b.candidate.movementType,'unknown');assert.equal(b.candidate.movementEvidence,'inferred')});
test('contrato fictício mantém NUMREG e posição do extrato',()=>{assert.equal(vehicle.datasetMode,'synthetic');const records=sheetRecords(vehicle);assert.equal(records.length,vehicle.parts.length);assert.ok(records.every(r=>r.document&&r.sourceLine));const r=analyzeStock(item,records,catalog,options);assert.ok(['old','inconclusive','validated','incomplete'].includes(r.status));if(r.latest){const original=vehicle.parts.find(p=>p[6]===r.latest.sourceLine);assert.equal(r.latest.document,original[8]);assert.equal(r.latest.km,original[2]);assert.equal(r.latest.time,null)}});
function testDb(){const sqlite=new DatabaseSync(':memory:');for(const file of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(n=>n.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));return {sqlite,prepare(sql){let args=[];return {bind(...a){args=a;return this},async run(){return sqlite.prepare(sql).run(...args)},async all(){return {results:sqlite.prepare(sql).all(...args)}}}},async batch(statements){sqlite.exec('BEGIN');try{const r=[];for(const statement of statements)r.push(await statement.run());sqlite.exec('COMMIT');return r}catch(e){sqlite.exec('ROLLBACK');throw e}}}}
test('migrações + gravação real SQLite: repetir lote não duplica nem substitui resultados',async()=>{const db=testDb(),r=analyze([row()]),hash=await digest('request');await saveSnapshots(db,'owner-A',new Map([['0',hash]]),[r]);const changed={...r,id:crypto.randomUUID(),latest:row({km:90000}),sourceVersion:'v2'};await saveSnapshots(db,'owner-A',new Map([['0',hash]]),[changed]);const rows=db.sqlite.prepare('SELECT snapshot FROM query_history WHERE owner_id=?').all('owner-A');assert.equal(rows.length,1);assert.equal(JSON.parse(rows[0].snapshot).latest.km,82450);assert.equal(JSON.parse(rows[0].snapshot).sourceVersion,'v1');db.sqlite.close()});
test('nova pesquisa preserva a anterior e consultas de outro proprietário ficam separadas',async()=>{const db=testDb(),first=analyze([row()]),hashes=new Map([['0','request']]);await saveSnapshots(db,'owner-A',hashes,[first]);const next={...analyze([row({date:'2026-09-20',km:90000})]),runId:'TEST-RUN-00000002'};await saveSnapshots(db,'owner-A',hashes,[next]);await saveSnapshots(db,'owner-B',hashes,[{...first,id:crypto.randomUUID()}]);const rows=db.sqlite.prepare('SELECT snapshot FROM query_history WHERE owner_id=? ORDER BY created_at,id').all('owner-A');assert.equal(rows.length,2);assert.deepEqual(rows.map(r=>JSON.parse(r.snapshot).latest.km).sort(),[82450,90000]);assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM query_history WHERE owner_id=?').get('owner-B').n,1);assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM query_history WHERE owner_id=? AND json_extract(snapshot,\'$.validated\')=1').get('owner-A').n,2);db.sqlite.close()});

test('serviço de consulta lê as fontes, mantém O.S./ficha e processa lote com exemplos fictícios',async()=>{
 const {createSearchContext,executeSearchItem}=await import('../lib/search-service.ts');
 const assets={async fetch(request){const path=new URL(request.url).pathname;return new Response(fs.readFileSync(new URL('../public'+path,import.meta.url)),{headers:{'Content-Type':'application/json'}})}};
 const context=await createSearchContext('test','sheets',assets,null);
 const os=await executeSearchItem({key:'1',prefix:'',part:'Pergunta livre',query:'Peças da O.S. 700.001 no prefixo 55154',kind:'query'},context,options);
 assert.equal(os.status,'records_found');assert.ok(os.evidence.length);assert.ok(os.evidence.every(r=>r.workOrder==='700001'));
 const service=await executeSearchItem({key:'2',prefix:'',part:'Pergunta livre',query:'Ficha 800.001 prefixo 55154',kind:'query'},context,options);
 assert.equal(service.status,'service_found');assert.equal(service.service.ficha,'800001');
 const batch=parseBatch('55154 → Bico Injetor, Kit de Embreagem\n55125 → Turbina, Filtro de Ar').items;
 const results=await Promise.all(batch.map(i=>executeSearchItem(i,context,options)));
 assert.equal(results.length,4);assert.ok(results.every(r=>r.sourceVersion.length>64));assert.ok(results.every(r=>r.query&&r.queriedAt));
});
test('CSV sem código reconhece apenas nomes exatos das peças-mãe',()=>{const r=analyze([row({code:'',part:'Bico Injetor'})]);assert.equal(r.validated,true);assert.equal(analyze([row({code:'',part:'Reparo do Bico Injetor'})]).status,'not_found')});

test('devolução fora do período selecionado continua bloqueando a saída vinculada',()=>{const issue=row();const negative=row({id:'NEG-FORA',date:'2026-09-20',quantity:-1,movement:'return',explicitIssue:false});const r=analyze([issue],{reconciliationRecords:[issue,negative]});assert.equal(r.validated,false);assert.equal(r.latest,null);assert.ok(r.evidence.some(e=>e.id==='NEG-FORA'));assert.ok(r.warnings.some(w=>w.includes('fora do período')))});
