import type {SearchSnapshot,SourceMode} from './validated-search.ts';
export const systems=[{id:'motor',label:'Motor',query:'Motor',families:['motor'],x:620,y:190},{id:'transmissao',label:'Transmissão',query:'Câmbio',families:['cambio e embreagem','transmissao'],x:500,y:200},{id:'freios',label:'Freios',query:'Freio',families:['freios','freio'],x:275,y:245},{id:'arrefecimento',label:'Arrefecimento',query:'Radiador',families:['arrefecimento'],x:700,y:180},{id:'eletrico',label:'Elétrico',query:'Bateria',families:['eletrica','eletrico','sistema eletrico'],x:180,y:165}] as const;
export type SystemId=typeof systems[number]['id'];
export type InvestigationIntent={id:string;prefix:string;part?:string;query?:string;system?:SystemId;sourceMode?:SourceMode;recentDays?:number};
export type CognitiveIndex={generatedAt:string;latest:string;vehicles:Record<string,{systems:Record<string,{count:number;last:string}>;repeats:{part:string;documents:number}[]}>};
export function clientId(){return Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join('')}
export function confidenceFor(r:SearchSnapshot){return r.validated?{label:r.incomplete?'Saída comprovada · dados incompletos':'Evidência documental suficiente',tone:r.incomplete?'attention':'verified',description:'Documento, quantidade e origem atendem às regras de saída. Não é uma probabilidade de instalação ou de diagnóstico.'}:r.status==='service_found'?{label:'Serviço localizado · saída não confirmada',tone:'attention',description:'A fonte confirma um serviço; não comprova a saída de uma peça.'}:{label:r.status==='not_found'?'Sem evidência localizada':'Evidência insuficiente ou divergente',tone:'attention',description:'Não há base confiável para confirmar uma saída. Revise os registros de origem.'}}
export function snapshotChanges(a:SearchSnapshot,b:SearchSnapshot){
 const criteria=[['Prefixo',a.prefix,b.prefix],['Peça pesquisada',a.part,b.part],['Peça interpretada',a.resolvedPart,b.resolvedPart],['Pergunta',a.query,b.query],['Origem selecionada',a.sourceMode,b.sourceMode],['Antiguidade após (dias)',a.recentDays,b.recentDays]];
 const fields=[['Status',a.status,b.status],['Saída validada',a.validated,b.validated],['Lançamento',a.latest?.document,b.latest?.document],['Registro',a.latest?.id,b.latest?.id],['Data',a.latest?.date,b.latest?.date],['Horário',a.latest?.time,b.latest?.time],['KM',a.latest?.km,b.latest?.km],['Quantidade',a.latest?.quantity,b.latest?.quantity],['Responsável',a.latest?.responsible,b.latest?.responsible],['O.S.',a.latest?.workOrder,b.latest?.workOrder],['Arquivo',a.latest?.sourceFile,b.latest?.sourceFile],['Posição',a.latest?.sourceLine,b.latest?.sourceLine],['Registros correspondentes',a.matchedCount,b.matchedCount],['Registros excluídos',a.excludedCount,b.excludedCount],['Dados incompletos',a.incomplete,b.incomplete],['Data do serviço',a.service?.date,b.service?.date],['Ficha',a.service?.ficha,b.service?.ficha],['Providência',a.service?.action,b.service?.action],['Defeito alegado',a.service?.alleged,b.service?.alleged],['Responsável pelo serviço',a.service?.responsible,b.service?.responsible],['Explicação',a.explanation,b.explanation],['Fonte',a.sourceVersion,b.sourceVersion],['Regras',a.ruleVersion,b.ruleVersion]];
 const display=(v:unknown)=>typeof v==='boolean'?(v?'Sim':'Não'):String(v??'Não informado');
 return [...criteria,...fields].filter(([,x,y])=>x!==y).map(([field,before,after])=>({field:String(field),before:display(before),after:display(after)}));
}
