"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowUpRight,X,Check,CheckCircle2,Clock3,Copy,Download,FileSearch,History,Layers3,ListFilter,LoaderCircle,Search,ShieldCheck,TriangleAlert} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Combobox,ComboboxContent,ComboboxInput,ComboboxItem,ComboboxList,ComboboxEmpty,ComboboxTrigger} from "@/components/ui/combobox";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Progress} from "@/components/ui/progress";
import {formatDate,formatRecordNumber,normalize,type CatalogData,type Summary} from "@/lib/fleet";
import {normalizeOperationalPrefix} from "@/lib/import-pipeline";
import {parseBatch,statusLabels,type SearchItem,type SearchSnapshot,type SourceMode,type ValidationStatus} from "@/lib/validated-search";
import {EvidenceComparison} from "@/components/cognitive/evidence-comparison";
import {HumanReview} from '@/components/cognitive/human-review';
import {InvestigationContext} from '@/components/cognitive/investigation-context';
import {CommandBar} from '@/components/cognitive/command-bar';
import {CriteriaEditor} from '@/components/cognitive/criteria-editor';
import {interpretQuery,withVehicleContext} from '@/lib/query-engine';
import {csvDocument,downloadData} from '@/lib/export-data';
import {confidenceFor,systems,type SystemId,type CognitiveIndex,type InvestigationIntent} from '@/lib/cognitive';
const n=(x:number)=>x.toLocaleString("pt-BR");
const moment=(s:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(s));
const km=(x:number|null|undefined)=>x==null?"Não informado":n(x)+" km";
export function Choice({label,value,onChange,options,disabled=false}:{label:string;value:string;onChange:(s:string)=>void;options:[string,string][];disabled?:boolean}){return <label className="research-field"><span>{label}</span><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger className="research-select" aria-label={label}><SelectValue/></SelectTrigger><SelectContent className="research-select-menu">{options.map(([key,text])=><SelectItem key={key} value={key}>{text}</SelectItem>)}</SelectContent></Select></label>}
export function ValidationBadge({status}:{status:ValidationStatus}){const good=["validated","old","incomplete"].includes(status);return <span className={`validation-badge status-${status}`}>{good?<ShieldCheck/>:status==="not_found"?<Search/>:<TriangleAlert/>}{statusLabels[status]}</span>}
function PartPicker({catalog,family,value,onChange,disabled}:{catalog:CatalogData|null;family:string;value:string;onChange:(s:string)=>void;disabled:boolean}){
 const anchor=useRef<HTMLDivElement>(null);
 const items=useMemo(()=>{if(!catalog)return [];const all=[...catalog.standardizedParts.filter(p=>family==="all"||p.families.includes(family)).map(p=>p.name),...(family==="all"?catalog.materials.map(p=>`${p.canonical} ${p.code}`):[])];return [...new Set(all)];},[catalog,family]);
 return <label className="research-field"><span>Peça ou código</span><div ref={anchor}><Combobox items={items} inputValue={value} onInputValueChange={(text,event)=>{if(["input-change","item-press","clear-press"].includes(event.reason))onChange(text)}} onValueChange={v=>{if(typeof v==="string")onChange(v)}} filter={(item,q)=>normalize(String(item)).includes(normalize(q))} limit={40} disabled={disabled}><ComboboxInput aria-label="Peça ou código" placeholder="Digite ou selecione a peça" showTrigger={false} showClear={false}><ComboboxTrigger aria-label="Abrir catálogo de peças"/><button type="button" aria-label="Limpar peça" disabled={!value||disabled} onClick={()=>onChange('')}><X size={16}/></button></ComboboxInput><ComboboxContent className="catalog-combobox-content" anchor={anchor}><ComboboxEmpty>Use o texto digitado para consultar.</ComboboxEmpty><ComboboxList>{(item:string)=><ComboboxItem key={item} value={item}>{item}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></div></label>
}
export function SearchWorkspace({summary,catalog,onHistory,onMaintenance,visible,intent,index}:{intent?:InvestigationIntent|null;index?:CognitiveIndex|null;summary:Summary|null;catalog:CatalogData|null;onHistory:()=>void;onMaintenance:(s:string)=>void;visible:boolean}){
 const [mode,setMode]=useState("single"),[prefix,setPrefix]=useState(""),[part,setPart]=useState(""),[family,setFamily]=useState("all"),[batch,setBatch]=useState(""),[question,setQuestion]=useState(""),[source,setSource]=useState<SourceMode>("sheets"),[days,setDays]=useState("180");
 const [vehicleCount,setVehicleCount]=useState(0);
 const [records,setRecords]=useState<SearchSnapshot[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[total,setTotal]=useState(0),[filter,setFilter]=useState("all"),[detail,setDetail]=useState<SearchSnapshot|null>(null);
 const [system,setSystem]=useState<SystemId>('motor');
 useEffect(()=>{if(!intent)return;const t=setTimeout(()=>{setPrefix(intent.prefix);if(intent.sourceMode)setSource(intent.sourceMode);if(intent.recentDays)setDays(String(intent.recentDays));if(intent.system)setSystem(intent.system);if(intent.part){setPart(intent.part);setMode('single')}else if(intent.query){setQuestion(intent.query);setMode('natural')}},0);return()=>clearTimeout(t)},[intent]);
 const contextQuestion=useMemo(()=>summary?withVehicleContext(question,prefix,summary,catalog):question,[question,prefix,summary,catalog]);
 const interpreted=useMemo(()=>summary&&question?interpretQuery(contextQuestion,summary,catalog):null,[question,contextQuestion,summary,catalog]);
 const focusVehicle=summary?.fleet.find(v=>'55'+v.code.padStart(3,'0')===(mode==='natural'&&interpreted?.prefix?'55'+interpreted.prefix.padStart(3,'0'):normalizeOperationalPrefix(prefix)))||null;
 const job=useRef<{runId:string;items:SearchItem[];sourceMode:SourceMode;recentDays:number;done:number}|null>(null),pause=useRef(false),running=useRef(false);
 const criteriaKey=JSON.stringify({mode,prefix,part,batch,question,source,days});
 const [submittedCriteria,setSubmittedCriteria]=useState('');
 useEffect(()=>()=>{pause.current=true},[]);
 const parsed=useMemo(()=>parseBatch(batch),[batch]);
 const families=useMemo(()=>[...new Set(catalog?.standardizedParts.flatMap(p=>p.families)||[])].sort(),[catalog]);
 async function execute(resume=false,questionOverride?:string){
  if(running.current)return;
  let current=job.current;
  if(!resume){let items:SearchItem[]=[];
   if(questionOverride||mode==="natural"){const q=(questionOverride||question).trim();if(!q){setError("Digite sua pergunta.");return;}items=[{key:"0",prefix:normalizeOperationalPrefix(prefix)||"",part:"Pergunta livre",query:q,kind:"query"}];}
   else if(mode==="batch"){if(parsed.errors.length||!parsed.items.length){setError(parsed.errors.join(" ")||"Inclua ao menos um prefixo e uma peça.");return;}items=parsed.items;}
   else {const p=normalizeOperationalPrefix(prefix);if(!p||!part.trim()){setError("Informe um prefixo de 001 a 559 e a peça desejada.");return;}items=[{key:"0",prefix:p,part:part.trim()}];}
   current={runId:Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,"0")).join(""),items,sourceMode:source,recentDays:Number(days),done:0};job.current=current;setSubmittedCriteria(criteriaKey);setRecords([]);setFilter("all");setTotal(items.length);setVehicleCount(new Set(items.map(i=>i.prefix).filter(Boolean)).size);
  }
  if(!current)return;running.current=true;setBusy(true);setError("");pause.current=false;
  try{while(current.done<current.items.length&&!pause.current){const slice=current.items.slice(current.done,current.done+5);const response=await fetch("/api/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({runId:current.runId,items:slice,sourceMode:current.sourceMode,recentDays:current.recentDays})});const data=await response.json() as {saved?:boolean;records:SearchSnapshot[];error?:string};if(!response.ok||!data.saved)throw new Error(data.error||"Não foi possível registrar a consulta.");setRecords(previous=>[...previous,...data.records]);current.done+=slice.length;}
  }catch(e){setError(e instanceof Error?e.message:"Falha na consulta.");}finally{running.current=false;setBusy(false);}
 }
 useEffect(()=>{if(!visible)return;const context=(document as Document&{modelContext?:{registerTool:(t:object,o:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{context.registerTool({name:"search_maintenance_history",title:"Consultar e registrar manutenção",description:"Consulta a fonte de manutenção e registra automaticamente o resultado no histórico permanente.",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input:{query:string}){if(typeof input.query!=="string"||input.query.length>500)throw new Error("Pergunta inválida.");setMode("natural");setQuestion(input.query);await execute(false,input.query);return {message:"Consulte os resultados e o estado de gravação exibidos no Jarvis."};}},{signal:controller.signal});}catch{}return()=>controller.abort();});
 const counts={confirmed:records.filter(r=>r.validated).length,not_found:records.filter(r=>r.status==="not_found").length,unconfirmed:records.filter(r=>!r.validated&&r.status!=="not_found").length,old:records.filter(r=>r.isOld).length,incomplete:records.filter(r=>r.incomplete).length};
 const shown=records.filter(r=>filter==="all"||filter==="confirmed"&&r.validated||filter==="unconfirmed"&&!r.validated&&r.status!=="not_found"||filter==="not_found"&&r.status==="not_found"||filter==="old"&&r.isOld||filter==="incomplete"&&r.incomplete);
 const pending=total>0&&records.length<total;
 return <div className={`research-workspace investigation-workspace mode-${mode} ${records.length?"has-results":""}`}><header className="investigation-heading"><div><span className="eyebrow">Investigação técnica</span><h1>Da consulta à evidência.</h1></div><button className="text-action" onClick={onHistory}><History/>Consultas anteriores</button></header><div className="investigation-workbench">
  <section className="research-composer surface">
   <div className="composer-heading"><div><span className="eyebrow">CRITÉRIOS DA CONSULTA</span><h2>O que vamos investigar?</h2></div><span className="quiet-label"><ShieldCheck/> Rastreabilidade por lançamento</span></div>
   <Tabs value={mode} onValueChange={setMode}><TabsList className="research-tabs"><TabsTrigger value="single" disabled={busy}><Search/>Uma peça</TabsTrigger><TabsTrigger value="batch" disabled={busy}><Layers3/>Em lote</TabsTrigger><TabsTrigger value="natural" disabled={busy}><FileSearch/>Pergunta livre</TabsTrigger></TabsList></Tabs>
   <form onSubmit={e=>{e.preventDefault();void execute();}}>
    {mode==="single"&&<div className="single-fields"><label className="research-field"><span>Prefixo</span><Input value={prefix} disabled={busy} inputMode="numeric" maxLength={5} onChange={e=>setPrefix(e.target.value)} placeholder="55154" aria-label="Prefixo da consulta"/></label><Choice label="Família" value={family} onChange={v=>{setFamily(v);setPart("")}} options={[["all","Pesquisa direta"],...families.map(x=>[x,x] as [string,string])]} disabled={busy}/><PartPicker catalog={catalog} family={family} value={part} onChange={setPart} disabled={busy}/></div>}
    {mode==="batch"&&<div className="batch-editor"><label className="research-field"><span>Uma linha por veículo. Separe as peças por vírgula.</span><Textarea value={batch} onChange={e=>setBatch(e.target.value)} disabled={busy} aria-label="Lista de veículos e peças" placeholder={"55154 → Bico Injetor, Kit de Embreagem, Óleo Motor\n55125 → Biturbo, Filtro de Ar\n55001 → Servo de Embreagem, Cilindro Mestre"} rows={5}/></label><div className="batch-interpretation"><span><b>{new Set(parsed.items.map(i=>i.prefix)).size}</b> veículos</span><span><b>{parsed.items.length}</b> consultas</span><span>Até 500 combinações</span>{parsed.duplicates>0&&<span>{parsed.duplicates} combinações repetidas reunidas</span>}</div>{parsed.errors.length>0&&<p className="inline-warning">{parsed.errors.slice(0,3).join(" ")}</p>}</div>}
    {mode==="natural"&&<label className="research-field question-field"><span>Pergunte por peça, prefixo, serviço, ficha ou O.S.</span><Input value={question} onChange={e=>setQuestion(e.target.value)} disabled={busy} maxLength={500} placeholder="Última saída de turbina do prefixo 55125" aria-label="Pergunta livre"/></label>}
    <div className="composer-footer"><div className="research-options"><Choice label="Fonte" value={source} onChange={v=>setSource(v as SourceMode)} options={[["sheets","Base integrada"],["csv","Meu CSV"]]} disabled={busy}/><Choice label="Considerar antigo após" value={days} onChange={setDays} options={[["30","30 dias"],["90","90 dias"],["180","180 dias"],["365","1 ano"],["730","2 anos"]]} disabled={busy}/></div><Button type="submit" className="primary-action" disabled={busy||!summary}>{busy?<LoaderCircle className="spin"/>:<Search/>}{busy?"Consultando…":mode==="batch"?"Pesquisar lote":"Pesquisar"}</Button></div>
   </form>
   {mode==='natural'&&contextQuestion!==question&&<p className="context-note">Esta pergunta usará o prefixo {normalizeOperationalPrefix(prefix)} selecionado. Mencione outro prefixo para trocar o contexto.</p>}
   {mode==='natural'&&interpreted&&<CriteriaEditor plan={interpreted} disabled={busy} onApply={setQuestion}/>}
   {interpreted?.issues?.length&&mode==='natural'&&<p className="inline-warning" role="status">{interpreted.issues.join(' ')}</p>}
   <p className="composer-note">Validação por documento, quantidade e origem. Devoluções e estornos relacionados exigem conferência. Saída não comprova instalação.</p>
  </section>
  {mode!=='batch'&&<InvestigationContext vehicle={focusVehicle} index={focusVehicle?index?.vehicles[focusVehicle.code]:undefined} selected={system} disabled={busy} onSystem={id=>{setSystem(id);if(focusVehicle)setPrefix('55'+focusVehicle.code.padStart(3,'0'));setFamily('all');setPart(systems.find(s=>s.id===id)!.query);setMode('single')}}/>}
  <aside className="investigation-answer" aria-label="Resposta e evidências" aria-busy={busy}>
   <div className="answer-heading"><ShieldCheck size={18}/><span>{busy?'Conferindo os registros':records.length===1?'Resultado preservado':'Evidências da consulta'}</span></div>
   {!!records.length&&submittedCriteria!==criteriaKey&&<p className="criteria-changed" role="status">Critérios editados. O resultado abaixo pertence à consulta anterior; pesquise novamente para aplicar as alterações.</p>}
   {records.length===1?<><SingleResult record={records[0]} onDetails={()=>setDetail(records[0])}/><div className={`confidence ${confidenceFor(records[0]).tone}`}><strong>{confidenceFor(records[0]).label}</strong><p>{confidenceFor(records[0]).description}</p></div><p className="answer-timestamp">Consulta de {moment(records[0].queriedAt)}. Alterar critérios não modifica este resultado.</p></>:<div className="answer-awaiting"><FileSearch size={32}/><h2>{busy?'Buscando saídas comprovadas…':records.length>1?`${records.length} resultados preservados`:'A evidência vem primeiro.'}</h2><p>{records.length>1?'Confira o resultado de cada veículo e peça na visão consolidada abaixo.':'A consulta verifica documento, quantidade e origem antes de confirmar a saída.'}</p><dl><div><dt>Documento</dt><dd>Identifica o lançamento de origem</dd></div><div><dt>Quantidade</dt><dd>Distingue saídas e movimentações</dd></div><div><dt>Rastreabilidade</dt><dd>Preserva fonte, linha e resultado</dd></div></dl><small>Não há diagnóstico ou compatibilidade presumidos.</small></div>}
  </aside></div>
  {error&&<div className="research-error" role="alert"><TriangleAlert/><div><strong>Esta etapa não foi concluída.</strong><p>{error}</p>{pending&&<Button onClick={()=>void execute(true)} disabled={busy}>Retomar consultas restantes</Button>}</div></div>}
  {(busy||total>0)&&<section className="batch-progress" aria-live="polite"><div><span>{busy?<LoaderCircle className="spin"/>:pending?<Clock3/>:<CheckCircle2/>}<strong>{busy?"Pesquisa em andamento":pending?"Pesquisa interrompida":"Pesquisa concluída"}</strong></span><span>{vehicleCount||"—"} veículos · {records.length} de {total} consultas registradas</span></div><Progress value={total?records.length/total*100:0} aria-label="Andamento da pesquisa"/>{busy&&<button type="button" onClick={()=>{pause.current=true}}>Parar após esta etapa</button>}{pending&&!busy&&!error&&<Button onClick={()=>void execute(true)}>Retomar</Button>}</section>}
  {records.length>0?<section className="research-results"><div className="results-heading"><div><span className="eyebrow">RESULTADO CONSOLIDADO</span><h2>{n(records.length)} consultas, uma visão completa.</h2></div><button className="text-action" onClick={onHistory}><History/>Ver histórico<ArrowUpRight/></button></div>{records.length>1&&<div className="result-metrics">{([["all",records.length,"Consultas"],["confirmed",counts.confirmed,"Com saída validada"],["unconfirmed",counts.unconfirmed,"Sem saída validada"],["not_found",counts.not_found,"Sem registros"]] as const).map(([key,value,label])=><button key={key} onClick={()=>setFilter(key)} aria-pressed={filter===key}><strong>{n(value)}</strong><span>{label}</span></button>)}</div>}<div className="result-controls">{records.length>1&&<div className="result-flags"><button aria-pressed={filter==="old"} onClick={()=>setFilter(filter==="old"?"all":"old")}><Clock3/>{counts.old} antigas</button><button aria-pressed={filter==="incomplete"} onClick={()=>setFilter(filter==="incomplete"?"all":"incomplete")}><ListFilter/>{counts.incomplete} incompletas</button></div>}<button className="text-action" onClick={()=>exportRecords(records)}><Download/>Exportar CSV</button></div>{records.length>1&&<ResultTable records={shown} onOpen={setDetail}/>}<p className="saved-note"><Check/>Resultados registrados no histórico. Cada nova pesquisa preserva a anterior.</p></section>:null}

  <div className="investigation-command"><span className="eyebrow">Refinar a investigação</span><CommandBar compact disabled={busy} catalog={catalog} prefix={prefix} onSubmit={q=>{setQuestion(q);setMode('natural');window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}}/></div>
  <QueryDetails record={detail} onClose={()=>setDetail(null)} onMaintenance={onMaintenance}/>
 </div>
}
function SingleResult({record:r,onDetails}:{record:SearchSnapshot;onDetails:()=>void}){
 const serviceOnly=r.queryDomain==='services'||r.status==='service_found';
 return <article className={"single-result surface result-"+(r.validated?"verified":"attention")}><div><span className="eyebrow">PREFIXO {r.prefix}</span><h3>{r.resolvedPart}</h3><ValidationBadge status={r.status}/></div>
 {serviceOnly?<><div className="single-result-facts"><div><span>Serviço localizado</span><strong>{r.service?formatDate(r.service.date):'Não localizado'}</strong></div><div><span>Nº Ficha</span><strong>{r.service?.ficha?formatRecordNumber(r.service.ficha):'Não informado'}</strong></div><div><span>Responsável na origem</span><strong>{r.service?.responsible||'Não informado'}</strong></div><div><span>Fonte / posição</span><strong>{r.service?`LISTAGEM GERAL · ${r.service.position}`:'Sem serviço confirmado'}</strong></div></div>{r.service?.alleged&&<p><b>Defeito alegado:</b> {r.service.alleged}</p>}{r.service?.action&&<p><b>Providência:</b> {r.service.action}</p>}<p className="context-note">Registro de serviço. A saída de peça e a quilometragem não são confirmadas por esta informação.</p></>:<div className="single-result-facts"><div><span>Última saída validada</span><strong>{r.latest?formatDate(r.latest.date):"Não localizada"}</strong></div><div><span>Quilometragem</span><strong>{km(r.latest?.km)}</strong></div><div><span>Lançamento</span><strong>{r.latest?.document||"—"}</strong></div><div><span>Fonte / posição</span><strong>{r.latest?`${r.latest.sourceFile} · ${r.latest.sourceLine??"não informada"}`:"Sem saída validada"}</strong></div></div>}
 <p>{r.explanation}</p><button className="text-action" onClick={onDetails}>Conferir evidências<ArrowUpRight/></button></article>
}
export function ResultTable({records,onOpen,history=false,onSelect,selected=[]}:{records:SearchSnapshot[];onOpen:(s:SearchSnapshot)=>void;history?:boolean;onSelect?:(s:SearchSnapshot)=>void;selected?:string[]}){const hasServices=records.some(r=>!r.latest&&!!r.service);return <div className="research-table-wrap"><table className="research-table"><thead><tr>{history&&<th>Consulta realizada</th>}<th>Veículo / peça</th><th>{hasServices?"Saída / serviço":"Última saída validada"}</th><th>Quilometragem</th><th>Status</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{records.map(r=><tr key={r.id}>{history&&<td data-label="Consulta"><time dateTime={r.queriedAt}>{moment(r.queriedAt)}</time><small>{r.sourceMode==="sheets"?"Planilhas integradas":"CSV complementar"}</small></td>}<td data-label="Veículo / peça"><button className="record-title" onClick={()=>onOpen(r)}><b>{r.prefix}</b><span>{r.resolvedPart}</span></button></td><td data-label={!r.latest&&r.service?"Serviço localizado":"Última saída validada"}>{r.latest?<><strong>{formatDate(r.latest.date)}</strong><small>{r.latest.time||"Horário não informado"}</small></>:r.service?<><strong>{formatDate(r.service.date)}</strong><small>Serviço · Ficha {r.service.ficha?formatRecordNumber(r.service.ficha):"não informada"} · saída não confirmada</small></>:<span className="muted-text">Não localizada</span>}</td><td data-label="KM">{km(r.latest?.km)}</td><td data-label="Validação"><ValidationBadge status={r.status}/>{r.isOld&&r.incomplete&&<small>Também possui dados incompletos</small>}</td><td className="row-actions"><button aria-label={`Detalhes da consulta de ${r.resolvedPart} no prefixo ${r.prefix}`} onClick={()=>onOpen(r)}><ArrowUpRight/></button>{onSelect&&<button aria-label={`Comparar consulta ${r.id}`} aria-pressed={selected.includes(r.id)} onClick={()=>onSelect(r)}>{selected.includes(r.id)?<Check/>:<Copy/>}</button>}</td></tr>)}</tbody></table>{!records.length&&<div className="research-list-empty"><FileSearch/><p>Nenhuma consulta corresponde aos filtros.</p></div>}</div>}
export function QueryDetails({record:r,onClose,onMaintenance,onReopen}:{record:SearchSnapshot|null;onClose:()=>void;onMaintenance?:(s:string)=>void;onReopen?:(r:SearchSnapshot)=>void}){
 const serviceOnly=!!r&&!r.latest&&(r.queryDomain==='services'||r.status==='service_found');
 return <Sheet open={!!r} onOpenChange={open=>{if(!open)onClose()}}>
  <SheetContent className="query-detail-sheet">
   <SheetHeader><SheetTitle>{r?.resolvedPart||'Detalhes da consulta'}</SheetTitle><SheetDescription>{r?'Prefixo '+r.prefix+' · Pesquisado em '+moment(r.queriedAt):'Registro preservado'}</SheetDescription></SheetHeader>
   {r&&<div className="query-detail-body">
    <ValidationBadge status={r.status}/><p className="detail-explanation">{r.explanation}</p>
    <dl className="detail-facts">{serviceOnly?<><Fact label="Serviço localizado" value={r.service?formatDate(r.service.date):'Não localizado'}/><Fact label="Nº Ficha" value={r.service?.ficha?formatRecordNumber(r.service.ficha):'Não informado'}/><Fact label="Responsável pelo serviço" value={r.service?.responsible||'Não informado'}/><Fact label="Posição na Planilha" value={r.service?'LISTAGEM GERAL · '+r.service.position:'Sem serviço confirmado'}/><Fact label="Confirmação de saída" value="O registro de serviço não comprova saída de peça."/></>:<>
     <Fact label="Última saída validada" value={r.latest?formatDate(r.latest.date):'Não localizada'}/><Fact label="Horário da saída" value={r.latest?.time||'Não informado'}/><Fact label="Quilometragem" value={km(r.latest?.km)}/><Fact label="Quantidade" value={r.latest?.quantity==null?'Não informada':n(r.latest.quantity)}/><Fact label="Nº do lançamento" value={r.latest?.document||'Não informado'}/><Fact label="O.S." value={r.latest?.workOrder?formatRecordNumber(r.latest.workOrder):'Não informada'}/><Fact label="Responsável na origem" value={r.latest?.responsible||'Não informado'}/>
    </>}</dl>
    {r.checks.length>0&&<section><h3>Critérios conferidos</h3><ul className="evidence-checks">{r.checks.map(c=><li key={c.label}>{c.passed?<CheckCircle2/>:<TriangleAlert/>}{c.label}</li>)}</ul></section>}
    {r.warnings.length>0&&<div className="detail-warnings">{r.warnings.map((w,i)=><p key={i}>{w}</p>)}</div>}
    {r.service&&<section className="evidence-record"><h3>{serviceOnly?'Registro do serviço':'Serviço relacionado'}</h3>{r.service.alleged&&<p><b>Defeito alegado:</b> {r.service.alleged}</p>}{r.service.action&&<p><b>Providência:</b> {r.service.action}</p>}<small>{formatDate(r.service.date)} - Nº Ficha: {r.service.ficha?formatRecordNumber(r.service.ficha):'Não informado'} - Posição na Planilha: {r.service.position} - LISTAGEM GERAL</small></section>}
    <section><h3>Registros considerados</h3><p className="muted-text">{serviceOnly?r.matchedCount+' serviços correspondentes; nenhum deles é apresentado como comprovação de saída.':r.matchedCount+' correspondências · '+r.excludedCount+' sem elegibilidade para saída validada'}</p>
     {r.evidence.map(e=><article className="evidence-record" key={e.id}>
      <div><strong>{e.part}</strong><span>{formatDate(e.date)}</span></div>
      {e.family&&<p>Família: {e.family}</p>}
      <p>{e.sourceFile} - Posição na Planilha: {e.sourceLine??'não disponível'} - Nº do lançamento: {e.document||'não disponível'}</p>
      <small>ID {e.id} - Quantidade: {e.quantity??'não informada'} - KM: {e.km==null?'não informado':n(e.km)}</small>
      <small>Natureza: {e.source==='EXTRATO GERAL'&&e.quantity!==null&&e.quantity<0?'Movimento negativo · natureza não informada':({issue:'Saída registrada',return:'Devolução',reversal:'Estorno',entry:'Entrada',adjustment:'Ajuste',unknown:'Não identificada'} as Record<string,string>)[e.movement]||'Não identificada'} - O.S.: {e.workOrder?formatRecordNumber(e.workOrder):'não informada'} - Responsável: {e.responsible||'não informado'}</small>
      {r.assessments?.find(a=>a.recordId===e.id)?.reasons.map(reason=><p className="evidence-reason" key={reason}>{reason}</p>)}
     </article>)}
     {r.evidenceCount>r.evidence.length&&<p className="muted-text">Exibindo {r.evidence.length} registros de referência de {r.evidenceCount} analisados.</p>}
    </section>
    <details className="technical-trace"><summary>Rastreabilidade da consulta</summary><dl><Fact label="Pergunta original" value={r.query}/><Fact label="ID da consulta" value={r.id}/><Fact label="Lote" value={r.runId}/><Fact label="Versão das regras" value={r.ruleVersion}/><Fact label="Versão da fonte" value={r.sourceVersion}/><Fact label="Critério de antiguidade" value={r.recentDays+' dias'}/></dl></details>
    <EvidenceComparison key={'evidence-'+r.id} record={r}/><HumanReview key={r.id} record={r}/>
    {onReopen&&<button className="action-primary" onClick={()=>{onClose();onReopen(r)}}>Reabrir investigação com os mesmos critérios</button>}
    {onMaintenance&&/^55\d{3}$/.test(r.prefix)&&<button className="text-action" onClick={()=>{onClose();onMaintenance(String(Number(r.prefix)-55000))}}>Abrir manutenção do veículo<ArrowUpRight/></button>}
   </div>}
  </SheetContent>
 </Sheet>;
}
function Fact({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
export const recordExportHeader=['Consulta realizada (São Paulo)','Prefixo','Peça','Última saída validada','Horário','KM','Status','Quantidade','Nº lançamento','O.S.','Responsável','Arquivo','Linha','ID origem','ID consulta','Lote','Fonte selecionada','Versão da fonte','Versão das regras','Antiguidade após (dias)','Data do serviço','Nº Ficha','Defeito alegado','Providência','Responsável pelo serviço','Posição do serviço','Motivo'];
export function recordExportRow(r:SearchSnapshot){return [moment(r.queriedAt),r.prefix,r.resolvedPart,r.latest?.date||'',r.latest?.time||'',r.latest?.km??'',statusLabels[r.status],r.latest?.quantity??'',r.latest?.document||'',r.latest?.workOrder||'',r.latest?.responsible||'',r.latest?.sourceFile||'',r.latest?.sourceLine??'',r.latest?.id||'',r.id,r.runId,r.sourceMode,r.sourceVersion,r.ruleVersion,r.recentDays,r.service?.date||'',r.service?.ficha||'',r.service?.alleged||'',r.service?.action||'',r.service?.responsible||'',r.service?.position??'',r.explanation]}
export function exportRecords(records:SearchSnapshot[]){downloadData(csvDocument([recordExportHeader,...records.map(recordExportRow)]),'jarvis-consultas.csv','text/csv;charset=utf-8')}
